apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: farmvision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farmvision
      tier: database
  template:
    metadata:
      labels:
        app: farmvision
        tier: database
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: farmvision
        - name: POSTGRES_PASSWORD
          value: farmvisionpass
        - name: POSTGRES_DB
          value: farmvisiondb
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: farmvision
    tier: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP