apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: farmvision
spec:
  replicas: 2
  selector:
    matchLabels:
      app: farmvision
      tier: frontend
  template:
    metadata:
      labels:
        app: farmvision
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: farmvision-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: farmvision
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer