version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5433:5432" # Port local pour éviter conflit

  backend:
    build: ./backend
    command: sh -c "npm run migrate && npm test"
    environment:
      PGUSER: testuser
      PGPASSWORD: testpass
      PGHOST: db
      PGDATABASE: testdb
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    command: npx playwright test
    depends_on:
      backend:
        condition: service_completed_successfully