name: CI FarmVision Pro

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Backend Deps & Run Migrations
        run: |
          cd backend
          npm ci
          npm run migrate

      - name: Backend Tests
        run: |
          cd backend
          npm test

      - name: Install Frontend Deps
        run: |
          cd frontend
          npm ci

      - name: Run E2E Tests
        run: |
          cd frontend
          npx playwright test

      - name: Performance Tests
        run: |
          k6 run performance/load-test.js