name: FarmVision Pro - CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      - name: Run Backend Tests
        env:
          PGUSER: testuser
          PGPASSWORD: testpass
          PGHOST: localhost
          PGDATABASE: testdb
        run: |
          cd backend
          npm run migrate
          npm test

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Run Playwright Tests
        run: |
          cd frontend
          npx playwright test